# -*- coding: utf-8 -*-
"""Recommender System Wisata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDHFLLCon_DMj5UtfSD5Jj5rdHEOdi5p

#EDA
"""

# Import Library
import pandas as pd
import numpy as np
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (8, 5)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from google.colab import drive
drive.mount('/content/drive')

# Load Dataset
path = '/content/drive/MyDrive/Datmin/Data Destinasi Wisata.csv'
df = pd.read_csv(path)

print('Shape data:', df.shape)
df.head()

# Exploratory Data Analysis (EDA)

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

print("=== Info Data ===")
print(df.info())
print("\n=== Statistik Deskriptif (Numerik) ===")
display(df[['rating', 'fee']].describe())

print("\n=== 10 Kategori Terbanyak ===")
display(df['category'].value_counts().head(10))

print("\n=== 10 Kota Terbanyak ===")
display(df['city'].value_counts().head(10))

# --------------------------------------------------------------------
# Distribusi Rating
# --------------------------------------------------------------------
plt.figure(figsize=(8, 5))
sns.histplot(data=df, x='rating', bins=20, kde=True)
plt.title('Distribusi Rating Destinasi Wisata')
plt.xlabel('Rating')
plt.ylabel('Frekuensi')
plt.tight_layout()
plt.show()

# --------------------------------------------------------------------
# Distribusi Fee / Harga Tiket
# --------------------------------------------------------------------
plt.figure(figsize=(8, 5))
# Limit x-axis to 99th percentile to avoid one extreme outlier squashing the histogram
try:
    p99 = df['fee'].quantile(0.99)
    sns.histplot(data=df[df['fee'] <= p99], x='fee', bins=20, kde=True)
    outliers = int((df['fee'] > p99).sum())
    plt.title('Distribusi Fee / Harga Tiket Masuk (dikepang sampai 99th percentile)')
    if outliers > 0:
        plt.xlabel(f'Fee (Rp) — {outliers} outlier dikecualikan, geser batas untuk menampilkan)')
    else:
        plt.xlabel('Fee')
except Exception:
    sns.histplot(data=df, x='fee', bins=20, kde=True)
    plt.xlabel('Fee')

plt.ylabel('Frekuensi')
plt.tight_layout()
plt.show()

# --------------------------------------------------------------------
# Top 10 Kategori Destinasi
# --------------------------------------------------------------------
plt.figure(figsize=(8,4))
df['category'].value_counts().head(10).plot(kind='bar')
plt.title('Top 10 Kategori Destinasi')
plt.xlabel('Kategori')
plt.ylabel('Jumlah Destinasi')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# --------------------------------------------------------------------
# Jumlah Destinasi per Kota (Top 10 Kota)
# --------------------------------------------------------------------
plt.figure(figsize=(10, 5))
order_city = df['city'].value_counts().head(10).index
sns.countplot(data=df[df['city'].isin(order_city)], x='city', order=order_city)
plt.title('Top 10 Kota dengan Jumlah Destinasi Terbanyak')
plt.xlabel('Kota')
plt.ylabel('Jumlah Destinasi')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# --------------------------------------------------------------------
# Boxplot Outlier Rating & Fee
# --------------------------------------------------------------------
plt.figure(figsize=(6, 5))
df[['rating', 'fee']].boxplot()
plt.title('Boxplot Outlier Rating dan Fee')
plt.tight_layout()
plt.show()

# --------------------------------------------------------------------
# Distribusi Panjang Deskripsi (Jumlah Kata)
# --------------------------------------------------------------------
df['desc_word_count'] = df['deskripsi'].fillna("").apply(lambda x: len(x.split()))

plt.figure(figsize=(8, 5))
sns.histplot(df['desc_word_count'], bins=30, kde=True)
plt.title('Distribusi Panjang Deskripsi (Jumlah Kata)')
plt.xlabel('Jumlah Kata dalam Deskripsi')
plt.ylabel('Frekuensi')
plt.tight_layout()
plt.show()

# --------------------------------------------------------------------
# Distribusi Panjang Review (Jumlah Kata)
# --------------------------------------------------------------------
df['review_word_count'] = df['review'].fillna("").apply(lambda x: len(x.split()))

plt.figure(figsize=(8, 5))
sns.histplot(df['review_word_count'], bins=30, kde=True)
plt.title('Distribusi Panjang Review (Jumlah Kata)')
plt.xlabel('Jumlah Kata dalam Review')
plt.ylabel('Frekuensi')
plt.tight_layout()
plt.show()

"""#Korelasi"""

# === Analisis Korelasi ===

# Memilih hanya kolom numerik
numeric_cols = df.select_dtypes(include=['int64', 'float64'])

# Menghitung korelasi
corr_matrix = numeric_cols.corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Heatmap Korelasi Antar Fitur Numerik")
plt.show()

corr_matrix

"""#Pre Process"""

# Text Mining & Pembuatan Fitur
def clean_text(text):
    text = str(text).lower()
    # hilangkan karakter non huruf/angka
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    # gabungkan spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# gabungkan deskripsi dan review
df['text'] = (df['deskripsi'].fillna('') + ' ' + df['review'].fillna('')).apply(clean_text)

# target klasifikasi
target_col = 'category'
y = df[target_col]

# fitur numerik, kategorikal, dan teks
numeric_features = ['rating', 'fee']
categorical_features = ['city']
text_feature = 'text'

X = df[numeric_features + categorical_features + [text_feature]]

X.head()

from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

# ============================
# 1. Filter kategori langka (<2 data)
# ============================
counts = df['category'].value_counts()
valid_classes = counts[counts >= 2].index

# Buang kelas yang hanya 1 baris
df_filtered = df[df['category'].isin(valid_classes)]

print("Jumlah data per kategori setelah filtering:")
print(df_filtered['category'].value_counts())

# Update X dan y sesuai df_filtered
X_filtered = X.loc[df_filtered.index]
y_filtered = df_filtered['category']


# ============================
# 2. Pembagian Dataset (Stratified)
# ============================
X_train, X_test, y_train, y_test = train_test_split(
    X_filtered,
    y_filtered,
    test_size=0.2,
    random_state=42,
    stratify=y_filtered
)

print("\nDistribusi kelas sebelum oversampling:")
print(Counter(y_train))


# ============================
# 3. Oversampling hanya pada data train
# ============================
oversampler = RandomOverSampler(random_state=42)
X_train_over, y_train_over = oversampler.fit_resample(X_train, y_train)

print("\nDistribusi kelas setelah oversampling:")
print(Counter(y_train_over))

numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
text_transformer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features),
        ('txt', text_transformer, text_feature)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
    # Removed stratify=y to fix the ValueError
)

print('Train size:', X_train.shape)
print('Test size :', X_test.shape)

display(df['category'].value_counts())

# Fungsi Evaluasi KNN (Akurasi, Precision, Recall, F1)

def evaluate_knn(n_neighbors, weights='uniform', metric='minkowski', p=2):
    """
    Evaluasi model KNN dengan pipeline preprocessing.
    Mengembalikan: akurasi, precision, recall, f1, dan model terlatih.
    """
    clf = Pipeline(steps=[
        ('preprocess', preprocessor),
        ('model', KNeighborsClassifier(
            n_neighbors=n_neighbors,
            weights=weights,
            metric=metric,
            p=p
        ))
    ])

    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='macro', zero_division=0)
    rec  = recall_score(y_test, y_pred, average='macro', zero_division=0)
    f1   = f1_score(y_test, y_pred, average='macro', zero_division=0)

    return acc, prec, rec, f1, clf

# Evaluasi 3 Skenario KNN

results = {}

# Skenario 1: k = 3, uniform
acc1, prec1, rec1, f1_1, model_sken1 = evaluate_knn(
    n_neighbors=3,
    weights='uniform'
)
results['Skenario 1'] = [acc1, prec1, rec1, f1_1]

# Skenario 2: k = 5, uniform
acc2, prec2, rec2, f1_2, model_sken2 = evaluate_knn(
    n_neighbors=5,
    weights='uniform'
)
results['Skenario 2'] = [acc2, prec2, rec2, f1_2]

# Skenario 3: k = 7, distance
acc3, prec3, rec3, f1_3, model_sken3 = evaluate_knn(
    n_neighbors=7,
    weights='distance'
)
results['Skenario 3'] = [acc3, prec3, rec3, f1_3]

# Buat tabel hasil evaluasi
eval_df = pd.DataFrame(
    results,
    index=['Akurasi', 'Precision', 'Recall', 'F1-Score']
).T

print("Hasil Evaluasi 3 Skenario:")
eval_df

print("\n=== Analisis Skenario Terbaik ===")

# Berdasarkan F1-Score
best_f1_scenario = eval_df['F1-Score'].idxmax()
best_f1_value = eval_df['F1-Score'].max()
print(f"Skenario terbaik berdasarkan F1-Score : {best_f1_scenario} (F1 = {best_f1_value:.4f})")

# Berdasarkan Akurasi
best_acc_scenario = eval_df['Akurasi'].idxmax()
best_acc_value = eval_df['Akurasi'].max()
print(f"Skenario terbaik berdasarkan Akurasi   : {best_acc_scenario} (Akurasi = {best_acc_value:.4f})")

# Berdasarkan Precision
best_prec_scenario = eval_df['Precision'].idxmax()
best_prec_value = eval_df['Precision'].max()
print(f"Skenario terbaik berdasarkan Precision : {best_prec_scenario} (Precision = {best_prec_value:.4f})")

# Berdasarkan Recall
best_rec_scenario = eval_df['Recall'].idxmax()
best_rec_value = eval_df['Recall'].max()
print(f"Skenario terbaik berdasarkan Recall    : {best_rec_scenario} (Recall = {best_rec_value:.4f})")

# Content-Based Recommendation

from sklearn.neighbors import NearestNeighbors

# Gunakan fitur yang sama seperti untuk training:
# numeric_features = ['rating', 'fee']
# categorical_features = ['city']
# text_feature = 'text'
# pastikan ketiga variabel di atas sudah didefinisikan di cell sebelumnya

# Bentuk kembali matriks fitur dari df (tidak pakai X lagi)
X_all = df[numeric_features + categorical_features + [text_feature]]

# Transform semua data ke ruang fitur yang sudah di-preprocess
# (preprocessor sudah di-fit saat training KNN classifier di cell 6–7)
X_all_vec = preprocessor.transform(X_all)

# Bangun model KNN untuk recommender (unsupervised)
knn_recommender = NearestNeighbors(
    n_neighbors=11,   # 1 (dirinya sendiri) + 10 rekomendasi
    metric='cosine',
    algorithm='brute'
)
knn_recommender.fit(X_all_vec)

def recommend_knn(place_name, top_n=10):
    """
    KNN-based recommender:
    Mengembalikan top_n tempat wisata yang paling mirip dengan place_name
    berdasarkan fitur:
    - rating (distandarkan)
    - fee (distandarkan)
    - city (one-hot)
    - text (TF-IDF deskripsi + review)
    """
    # Cari index tempat berdasarkan nama
    mask = df['place'].str.lower() == place_name.lower()
    if not mask.any():
        raise ValueError(f"Tempat '{place_name}' tidak ditemukan di dataset.")

    idx = df[mask].index[0]

    # Ambil vektor fitur tempat tersebut
    place_vec = X_all_vec[idx]

    # Cari K tetangga terdekat (K = top_n + 1 karena termasuk dirinya sendiri)
    distances, indices = knn_recommender.kneighbors(place_vec, n_neighbors=top_n + 1)

    # Buang dirinya sendiri (indeks pertama)
    rec_indices = indices[0][1:]
    rec_distances = distances[0][1:]

    # Susun hasil dalam DataFrame
    recs = df.iloc[rec_indices][['place', 'city', 'category', 'rating', 'fee', 'link']].copy()
    recs['similarity'] = 1 - rec_distances  # cosine similarity = 1 - distance

    # Urutkan dari kemiripan tertinggi
    recs = recs.sort_values(by='similarity', ascending=False)

    return recs

# Contoh pemanggilan:
contoh_tempat = df['place'].iloc[0]  # ambil satu tempat pertama di dataset
print("Tempat acuan:", contoh_tempat)
rekom_knn = recommend_knn(contoh_tempat, top_n=10)
rekom_knn

# Top 10 rekomendasi pantai

# 1) Ambil semua tempat yang kategorinya mengandung kata "pantai"
pantai_df = df[df['category'].str.contains('pantai', case=False, na=False)]

if pantai_df.empty:
    print("Tidak ada tempat dengan kategori yang mengandung 'pantai'.")
else:
    # 2) Pilih satu pantai dengan rating tertinggi sebagai anchor
    anchor_place = pantai_df.sort_values('rating', ascending=False)['place'].iloc[0]
    print("Anchor pantai (paling tinggi rating):", anchor_place)

    # 3) Gunakan KNN-based recommender untuk cari 10 tempat paling mirip
    top10_pantai = recommend_knn(anchor_place, top_n=10)

    print("\nTop 10 rekomendasi pantai (berdasarkan kemiripan dengan anchor):")
    display(top10_pantai)

mask_anak = df['category'].str.contains('anak', case=False, na=False)
anak_df = df[mask_anak].copy()

if anak_df.empty:
    print("Tidak ada kategori yang mengandung 'anak'.")
else:
    not_worth_anak = (
        anak_df
        .sort_values(by=['rating', 'fee'], ascending=[True, False])
        [['place', 'city', 'category', 'rating', 'fee', 'review', 'link']]
        .head(5)
    )

    print("Top 5 tempat wisata ANAK yang dianggap TIDAK worth to visit:")
    display(not_worth_anak)